name: Update Match Results

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Visa att workflow fungerar
        run: echo "Workflow fungerar!"